from st_aggrid import AgGrid
import streamlit as st
import pandas as pd
from streamlit_pandas_profiling import st_profile_report
from pandas_profiling import ProfileReport


st.set_page_config(layout='wide') #Choose wide mode as the default setting



#Add an app title. Use css to style the title
st.markdown(""" <style> .font {                                          
    font-size:30px ; font-family: 'Cooper Black'; color: #FF9633;} 
    </style> """, unsafe_allow_html=True)
st.markdown('<p class="font">select the table and generate the data profiling report</p>', unsafe_allow_html=True)

uploaded_file = st.sidebar.selectbox(
          'Select table',
          ('Table 1', 'Table 2'))


df = pd.read_csv('dataset/data.csv')


option1 = st.sidebar.radio(
  'What variables do you want to include in the report?',
  ('All cols', 'A subset of cols'))

if option1 == 'All cols':
  df = df

elif option1 == 'A subset of cols':
  var_list = list(df.columns)
  option3 = st.sidebar.multiselect(
       'Select variable(s) you want to include in the report.',
       var_list)
  df = df[option3]

option2 = st.sidebar.selectbox(
  'Choose Minimal Mode or Complete Mode',
  ('Minimal Mode', 'Complete Mode'))

if option2 == 'Complete Mode':
  mode = 'complete'
  st.sidebar.warning(
       'The default minimal mode disables expensive computations such as correlations and duplicate row detection. Switching to complete mode may cause the app to run overtime or fail for large datasets due to computational limit.')
elif option2 == 'Minimal Mode':
  mode = 'minimal'

grid_response = AgGrid(
  df,
  editable=True,
  height=300,
  width='100%',
)

updated = grid_response['data']
df1 = pd.DataFrame(updated)

if st.button('Generate Report'):
  if mode == 'complete':
       profile = ProfileReport(df,
                               title="User uploaded table",
                               progress_bar=True,
                               dataset={
                                    "description": 'This profiling report was generated by Insights Bees',
                                    "copyright_holder": 'Insights Bees',
                                    "copyright_year": '2022'
                               })
       st_profile_report(profile)
  elif mode == 'minimal':
       profile = ProfileReport(df1,
                               minimal=True,
                               title="User uploaded table",
                               progress_bar=True,
                               dataset={
                                    "description": 'This profiling report was generated by Insights Bees',
                                    "copyright_holder": 'Insights Bees',
                                    "copyright_year": '2022'
                               })
       st_profile_report(profile)